pipeline{
  agent any
  
  tools{
    maven "apache-maven-3.8.5"
  }

  stages {
    stage('SonarQube Analysis') {
      steps{
        //def mvn = tool 'apache-maven-3.8.5';
        withSonarQubeEnv() {
        // sh "${mvn}/bin/mvn clean verify sonar:sonar -Dsonar.projectKey=sonarqube1"
        sh "mvn clean verify sonar:sonar -Dsonar.projectKey=sonarqube1"
        }
      }
    }
  }
}
