pipeline
agent any
stages{
	stage('Build'){
		steps{
			echo "Building.............."
		}
	}
	stage('Test'){
		steps{
			echo "Testing..........."
		}
	}
	stage('Deploy'){
		steps{
			echo "Deploying.........."
		}
	}
	post{
		always{
			echo "Jenkinsfile run successfully........."
		}
		failure{
			echo "Jenkinsfile failed....."
		}
	}
}
