pipeline {
    agent any

    stages {
        stage('Connecting with GitHub') {
            steps {
                git branch: 'main', credentialsId: '64325d53-febd-4a54-a137-e7f06b24c2d6', url: 'https://github.com/heena-bansal-gemsol/EJ_Training.git'
                echo "Successfully Connected with git"
            }
        }
        stage('Building Docker Image') {
            steps{
                bat '''cd Heena/DockerUseCase2/
                    docker build -t heenagemini/heena:sampleApache1 .'''
            }
        }
        /*stage('Pushing Docker Image') {
            steps{
                bat "docker push heenagemini/heena:sampleApache1"
            }
        }*/
	stage('Stopping existing container') {
            steps{
                bat "docker stop sampleApache_container"
            }
        }
	stage('Removing container') {
            steps{
                bat "docker rm sampleApache_container"
            }
        }
	stage('Going to sleep (For checking downtime)') {
            steps{
                bat "timeout 60"
            }
        }
	stage('Run the image in container') {
            steps{
                bat "docker run -p 85:80 -d --name sampleApache_container heenagemini/heena:myapache"
            }
        }
    }
	post{
		always{
			echo "Jenkinsfile run successfully........."
		}
		failure{
			echo "Jenkinsfile failed....."
		}
	}
}

